name: Rust

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install gfortran
      run: brew install gfortran
    - name: Build
      run: cargo build --verbose
