name: Rust

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install gfortran
      run: brew cask install --appdir="/usr/local/bin/" gfortran
    #- name: Build
      #run: cargo build --verbose
