name: Rust

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install gfortran
      run: brew cask install gfortran
    - name: move it  
      run: mv /gfortran /usr/local/bin/
    #- name: Build
      #run: cargo build --verbose
