
name: Ubuntu
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install OpenBlas
        run:h
          sudo apt-get install -y xorg-dev libopenblas-dev
      - name: Build
        run: cargo build --verbose
        shell: bash
