name: Windows
on: [push]
env:
  MSYSTEM: MINGW64
  MSYS2_PATH_TYPE: inherit
  CC: gcc

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get OpenBlas
        run:
          c:\msys64\usr\bin\bash -l -c "pacman -S --noconfirm mingw-w64-x86_64-openblas"
      - name: Build
        run: |
          cargo build --verbose --target x86_64-pc-windows-gnu
